GET http://localhost:3000

###
GET http://localhost:3000/cats

###
GET http://localhost:3000/cats/error

###
GET http://localhost:3000/cats/error-request

###
GET http://localhost:3000/cats/id

###

POST http://localhost:3000/cats
content-type: application/json

{
  "name": "Fluffy",
  "age": 23,
  "breed": "Streets"
}